[package]
name = "psplash-rust"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/nguyenlkdn/psplash-rust.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drm = "0.9.0"
libdrm = "0.0.2"
